//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Organization { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public string Manager { get; set; }
        public int Quantity { get; set; }
        public decimal Summ { get; set; }
    }
}
